# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signInButton = QtWidgets.QPushButton(self.centralwidget)
        self.signInButton.setGeometry(QtCore.QRect(550, 310, 93, 28))
        self.signInButton.setObjectName("signInButton")
        self.canceButton = QtWidgets.QPushButton(self.centralwidget)
        self.canceButton.setGeometry(QtCore.QRect(50, 310, 93, 28))
        self.canceButton.setObjectName("canceButton")
        self.loginInput = QtWidgets.QLineEdit(self.centralwidget)
        self.loginInput.setGeometry(QtCore.QRect(50, 120, 113, 22))
        self.loginInput.setObjectName("loginInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(40, 170, 113, 22))
        self.passwordInput.setObjectName("passwordInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.signInButton.setText(_translate("MainWindow", "Войти"))
        self.canceButton.setText(_translate("MainWindow", "Отмена"))
