# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/changed_worker.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 258)
        MainWindow.setStyleSheet("background: #CF9292;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textSurname = QtWidgets.QTextEdit(self.centralwidget)
        self.textSurname.setGeometry(QtCore.QRect(250, 60, 104, 51))
        self.textSurname.setStyleSheet("background: #C4C4C4;")
        self.textSurname.setObjectName("textSurname")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(272, 40, 60, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 31, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 40, 60, 16))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.textName = QtWidgets.QTextEdit(self.centralwidget)
        self.textName.setGeometry(QtCore.QRect(100, 60, 104, 51))
        self.textName.setStyleSheet("background: #C4C4C4;")
        self.textName.setObjectName("textName")
        self.textPatr = QtWidgets.QTextEdit(self.centralwidget)
        self.textPatr.setGeometry(QtCore.QRect(400, 60, 104, 51))
        self.textPatr.setStyleSheet("background: #C4C4C4;")
        self.textPatr.setObjectName("textPatr")
        self.addWorkerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addWorkerButton.setGeometry(QtCore.QRect(172, 120, 261, 32))
        self.addWorkerButton.setStyleSheet("background: #C4C4C4;")
        self.addWorkerButton.setObjectName("addWorkerButton")
        self.txtErr = QtWidgets.QLabel(self.centralwidget)
        self.txtErr.setGeometry(QtCore.QRect(90, 170, 471, 31))
        self.txtErr.setText("")
        self.txtErr.setObjectName("txtErr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Фамилия"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
        self.label_3.setText(_translate("MainWindow", "Отчество "))
        self.addWorkerButton.setText(_translate("MainWindow", "Редактировать сотрудника"))
