# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_screen_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1023, 477)
        MainWindow.setStyleSheet("background: #F4F6F9;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(25, 51, 979, 381))
        self.widget.setStyleSheet("background: #5585B5;")
        self.widget.setObjectName("widget")
        self.changedButton = QtWidgets.QPushButton(self.widget)
        self.changedButton.setEnabled(True)
        self.changedButton.setGeometry(QtCore.QRect(650, 70, 321, 46))
        self.changedButton.setStyleSheet("border: 2px solid;\n"
"border-radius: 4px;\n"
"box-sizing: border-box;\n"
"cursor: pointer;\n"
"outline: none;\n"
"position: relative;\n"
"transition: 0.3s;\n"
"font-weight: 600;\n"
"vertical-align: middle;\n"
"background: #F27171;")
        self.changedButton.setObjectName("changedButton")
        self.delButton = QtWidgets.QPushButton(self.widget)
        self.delButton.setGeometry(QtCore.QRect(650, 130, 321, 46))
        self.delButton.setStyleSheet("border: 2px solid;\n"
"border-radius: 4px;\n"
"box-sizing: border-box;\n"
"cursor: pointer;\n"
"outline: none;\n"
"position: relative;\n"
"transition: 0.3s;\n"
"font-weight: 600;\n"
"vertical-align: middle;\n"
"background: #F27171;")
        self.delButton.setObjectName("delButton")
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setGeometry(QtCore.QRect(650, 10, 321, 46))
        self.addButton.setStyleSheet("border: 2px solid;\n"
"border-radius: 4px;\n"
"box-sizing: border-box;\n"
"cursor: pointer;\n"
"outline: none;\n"
"position: relative;\n"
"transition: 0.3s;\n"
"font-weight: 600;\n"
"vertical-align: middle;\n"
"background: #F27171;")
        self.addButton.setObjectName("addButton")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 632, 361))
        self.tableWidget.setStyleSheet("border: 2px solid;\n"
"border-radius: 4px;\n"
"box-sizing: border-box;\n"
"cursor: pointer;\n"
"outline: none;\n"
"position: relative;\n"
"transition: 0.3s;\n"
"font-weight: 600;\n"
"vertical-align: middle;\n"
"background: #F27171;")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(25, 20, 304, 23))
        self.comboBox.setStyleSheet("font-size: 14px;\n"
"    color: #66717f;\n"
"    padding: 0 14px;\n"
"    border: 2px solid;\n"
"    border-radius: 4px;\n"
"    box-sizing: border-box;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    position: relative;\n"
"    transition: 0.3s;\n"
"    font-weight: 600;\n"
"    vertical-align: middle;")
        self.comboBox.setObjectName("comboBox")
        self.directoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.directoryButton.setGeometry(QtCore.QRect(675, 20, 156, 23))
        self.directoryButton.setStyleSheet("font-size: 14px;\n"
"    color: #66717f;\n"
"    padding: 0 14px;\n"
"    border: 2px solid;\n"
"    border-radius: 4px;\n"
"    box-sizing: border-box;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    position: relative;\n"
"    transition: 0.3s;\n"
"    font-weight: 600;\n"
"    vertical-align: middle;")
        self.directoryButton.setObjectName("directoryButton")
        self.movementButton = QtWidgets.QPushButton(self.centralwidget)
        self.movementButton.setGeometry(QtCore.QRect(840, 20, 156, 23))
        self.movementButton.setStyleSheet("font-size: 14px;\n"
"    color: #66717f;\n"
"    padding: 0 14px;\n"
"    border: 2px solid;\n"
"    border-radius: 4px;\n"
"    box-sizing: border-box;\n"
"    cursor: pointer;\n"
"    outline: none;\n"
"    position: relative;\n"
"    transition: 0.3s;\n"
"    font-weight: 600;\n"
"    vertical-align: middle;")
        self.movementButton.setObjectName("movementButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.changedButton.setText(_translate("MainWindow", "Редактировать"))
        self.delButton.setText(_translate("MainWindow", "Удалить"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.directoryButton.setText(_translate("MainWindow", "Справочники"))
        self.movementButton.setText(_translate("MainWindow", "Движения"))
