# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 199)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addWorkerButton = QtWidgets.QPushButton(self.centralwidget)
        self.addWorkerButton.setGeometry(QtCore.QRect(0, 0, 191, 32))
        self.addWorkerButton.setObjectName("addWorkerButton")
        self.addTransactionButton = QtWidgets.QPushButton(self.centralwidget)
        self.addTransactionButton.setGeometry(QtCore.QRect(390, 70, 271, 32))
        self.addTransactionButton.setObjectName("addTransactionButton")
        self.addClientButton = QtWidgets.QPushButton(self.centralwidget)
        self.addClientButton.setGeometry(QtCore.QRect(370, 0, 191, 32))
        self.addClientButton.setObjectName("addClientButton")
        self.addShippingButton = QtWidgets.QPushButton(self.centralwidget)
        self.addShippingButton.setGeometry(QtCore.QRect(390, 100, 271, 32))
        self.addShippingButton.setObjectName("addShippingButton")
        self.addCourierButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCourierButton.setGeometry(QtCore.QRect(180, 0, 201, 32))
        self.addCourierButton.setObjectName("addCourierButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 100, 281, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 70, 281, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.addProductButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProductButton.setGeometry(QtCore.QRect(550, 0, 201, 32))
        self.addProductButton.setObjectName("addProductButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 731, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addWorkerButton.setText(_translate("MainWindow", "Добавить работника"))
        self.addTransactionButton.setText(_translate("MainWindow", "Зарегистрировать сделку"))
        self.addClientButton.setText(_translate("MainWindow", "Добавить клиента"))
        self.addShippingButton.setText(_translate("MainWindow", "Оформить доставку"))
        self.addCourierButton.setText(_translate("MainWindow", "Добавить курьера"))
        self.pushButton_6.setText(_translate("MainWindow", "Проверить остаток товара на складе"))
        self.pushButton_7.setText(_translate("MainWindow", "Оформить загрузку/отгрузку товара"))
        self.addProductButton.setText(_translate("MainWindow", "Добавить товар"))
