# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 283)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.priceLine = QtWidgets.QLineEdit(self.centralwidget)
        self.priceLine.setObjectName("priceLine")
        self.gridLayout.addWidget(self.priceLine, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.measurmentLine = QtWidgets.QLineEdit(self.centralwidget)
        self.measurmentLine.setObjectName("measurmentLine")
        self.gridLayout.addWidget(self.measurmentLine, 4, 2, 1, 1)
        self.nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLine.setObjectName("nameLine")
        self.gridLayout.addWidget(self.nameLine, 0, 2, 1, 1)
        self.prodAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prodAddBtn.setObjectName("prodAddBtn")
        self.gridLayout.addWidget(self.prodAddBtn, 5, 1, 1, 2)
        self.producerLine = QtWidgets.QLineEdit(self.centralwidget)
        self.producerLine.setObjectName("producerLine")
        self.gridLayout.addWidget(self.producerLine, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить новый товар"))
        self.label_2.setText(_translate("MainWindow", "Цена"))
        self.label_4.setText(_translate("MainWindow", "Ед. измерения"))
        self.label.setText(_translate("MainWindow", "Наименование"))
        self.label_3.setText(_translate("MainWindow", "Производитель"))
        self.prodAddBtn.setText(_translate("MainWindow", "Добавить"))
