# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import worker
import numpy as np
import pandas as pd
import sys
from PyQt5 import QtWidgets
import main_screen
import re
from main import WorkerUI, Worker
from clients import ClientUI
from product import ProductUi
from courier import CourierUI
from accessify import protected

class Main_Screen(QtWidgets.QMainWindow, main_screen.Ui_MainWindow):
    def __init__(self):
        # Это здесь нужно для доступа к переменным, методам
        # и т.д. в файле design.py
        super().__init__()
        self.setupUi(self)  # Это нужно для инициализации нашего дизайна
        self.addWorkerButton.clicked.connect(self.openWorker)
        self.addClientButton.clicked.connect(self.openClient)
        self.addProductButton.clicked.connect(self.openProduct)
        self.addCourierButton.clicked.connect(self.openCourier)
        self.addTransactionButton.clicked.connect(self.openTransaction)
        self.addShippingButton.clicked.connect(self.openShipping)

    def openWorker(self):
        self.work = WorkerUI()
        self.work.show()
        self.hide()

    def openClient(self):
        self.work = ClientUI()
        self.work.show()
        self.hide()

    def openProduct(self):
        self.work = ProductUi()
        self.work.show()
        self.hide()

    def openCourier(self):
        self.work = CourierUI()
        self.work.show()
        self.hide()

    def openTransaction(self):
        pass

    def openShipping(self):
        pass


def main():
    app = QtWidgets.QApplication(sys.argv)  # Новый экземпляр QApplication
    window = Main_Screen()  # Создаём объект класса ExampleApp
    window.show()  # Показываем окно
    app.exec_()  # и запускаем приложение

if __name__ == '__main__':  # Если мы запускаем файл напрямую, а не импортируем
    main()  # то запускаем функцию main()
