# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/shipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Product = QtWidgets.QComboBox(self.centralwidget)
        self.Product.setGeometry(QtCore.QRect(280, 60, 151, 41))
        self.Product.setObjectName("Product")
        self.Courier = QtWidgets.QComboBox(self.centralwidget)
        self.Courier.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.Courier.setObjectName("Courier")
        self.Address = QtWidgets.QComboBox(self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(630, 60, 151, 41))
        self.Address.setObjectName("Address")
        self.Client = QtWidgets.QComboBox(self.centralwidget)
        self.Client.setGeometry(QtCore.QRect(480, 60, 151, 41))
        self.Client.setObjectName("Client")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 70, 110, 24))
        self.dateEdit.setObjectName("dateEdit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(430, 70, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 110, 181, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Добавить доставку"))
