# -*- coding: utf-8 -*-

<<<<<<< HEAD
# Form implementation generated from reading ui file '.\ui\shipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
=======
# Form implementation generated from reading ui file 'ui/shipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
>>>>>>> 41fd03c46743a4e67b4bd2a698114aaa2c51f059
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
<<<<<<< HEAD
        MainWindow.resize(481, 108)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lCourier = QtWidgets.QLabel(self.centralwidget)
        self.lCourier.setAlignment(QtCore.Qt.AlignCenter)
        self.lCourier.setObjectName("lCourier")
        self.verticalLayout.addWidget(self.lCourier)
        self.courier = QtWidgets.QLineEdit(self.centralwidget)
        self.courier.setObjectName("courier")
        self.verticalLayout.addWidget(self.courier)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lData = QtWidgets.QLabel(self.centralwidget)
        self.lData.setAlignment(QtCore.Qt.AlignCenter)
        self.lData.setObjectName("lData")
        self.verticalLayout_2.addWidget(self.lData)
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lProduct = QtWidgets.QLabel(self.centralwidget)
        self.lProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.lProduct.setObjectName("lProduct")
        self.verticalLayout_3.addWidget(self.lProduct)
        self.product = QtWidgets.QLineEdit(self.centralwidget)
        self.product.setObjectName("product")
        self.verticalLayout_3.addWidget(self.product)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lAmount = QtWidgets.QLabel(self.centralwidget)
        self.lAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.lAmount.setObjectName("lAmount")
        self.verticalLayout_4.addWidget(self.lAmount)
        self.amount = QtWidgets.QLineEdit(self.centralwidget)
        self.amount.setObjectName("amount")
        self.verticalLayout_4.addWidget(self.amount)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lClient = QtWidgets.QLabel(self.centralwidget)
        self.lClient.setAlignment(QtCore.Qt.AlignCenter)
        self.lClient.setObjectName("lClient")
        self.verticalLayout_5.addWidget(self.lClient)
        self.client = QtWidgets.QLineEdit(self.centralwidget)
        self.client.setObjectName("client")
        self.verticalLayout_5.addWidget(self.client)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lAdress = QtWidgets.QLabel(self.centralwidget)
        self.lAdress.setAlignment(QtCore.Qt.AlignCenter)
        self.lAdress.setObjectName("lAdress")
        self.verticalLayout_6.addWidget(self.lAdress)
        self.adress = QtWidgets.QLineEdit(self.centralwidget)
        self.adress.setObjectName("adress")
        self.verticalLayout_6.addWidget(self.adress)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.acceptButton = QtWidgets.QPushButton(self.centralwidget)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_2.addWidget(self.acceptButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
=======
        MainWindow.resize(815, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Product = QtWidgets.QComboBox(self.centralwidget)
        self.Product.setGeometry(QtCore.QRect(280, 60, 151, 41))
        self.Product.setObjectName("Product")
        self.Courier = QtWidgets.QComboBox(self.centralwidget)
        self.Courier.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.Courier.setObjectName("Courier")
        self.Address = QtWidgets.QComboBox(self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(630, 60, 151, 41))
        self.Address.setObjectName("Address")
        self.Client = QtWidgets.QComboBox(self.centralwidget)
        self.Client.setGeometry(QtCore.QRect(480, 60, 151, 41))
        self.Client.setObjectName("Client")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 70, 110, 24))
        self.dateEdit.setObjectName("dateEdit")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(430, 70, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 110, 181, 32))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
>>>>>>> 41fd03c46743a4e67b4bd2a698114aaa2c51f059

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
<<<<<<< HEAD
        self.lCourier.setText(_translate("MainWindow", "Курьер"))
        self.lData.setText(_translate("MainWindow", "Дата"))
        self.lProduct.setText(_translate("MainWindow", "Товар"))
        self.lAmount.setText(_translate("MainWindow", "Количество"))
        self.lClient.setText(_translate("MainWindow", "Клиент"))
        self.lAdress.setText(_translate("MainWindow", "Адрес"))
        self.cancelButton.setText(_translate("MainWindow", "Отменить"))
        self.acceptButton.setText(_translate("MainWindow", "Принять"))
=======
        self.pushButton.setText(_translate("MainWindow", "Добавить доставку"))
>>>>>>> 41fd03c46743a4e67b4bd2a698114aaa2c51f059
